# Generated by Django 3.0.7 on 2020-09-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200907_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_order',
            field=models.CharField(default='', max_length=254),
        ),
    ]
