# Generated by Django 3.0.7 on 2020-08-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200829_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='original_basket',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_pid',
        ),
    ]
