# Generated by Django 3.0.7 on 2020-08-31 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '__first__'),
        ('checkout', '0006_auto_20200831_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='myprofile.UserAccount'),
        ),
    ]
