# Generated by Django 3.0.7 on 2020-08-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='course',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]