# Generated by Django 3.0.7 on 2020-12-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
